### Task1

In [211]:
import numpy as np

In [212]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [213]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

### Task2

In [214]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task3

In [215]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [216]:
a_centered_sp / 4

2.0

### Task4

In [217]:
np.cov(a.T)[0, 1]

2.0

### Task5

In [218]:
import pandas as pd

In [219]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                        'author_name': ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [220]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Task6

In [221]:
authors_price = pd.merge(authors, book, on='author_id').reset_index()
authors_price

index  author_id author_name            book_title  price
0      0          1    Тургенев           Отцы и дети    450
1      1          1    Тургенев                 Рудин    300
2      2          1    Тургенев     Дворянское гнездо    350
3      3          2       Чехов      Толстый и тонкий    500
4      4          2       Чехов       Дама с собачкой    450
5      5          3  Островский                 Гроза    370
6      6          3  Островский  Таланты и поклонники    290

### Task7

In [222]:
top5 = authors_price.nlargest(5, 'price')
top5 = top5.reset_index()
top5

level_0  index  author_id author_name         book_title  price
0        3      3          2       Чехов   Толстый и тонкий    500
1        0      0          1    Тургенев        Отцы и дети    450
2        4      4          2       Чехов    Дама с собачкой    450
3        5      5          3  Островский              Гроза    370
4        2      2          1    Тургенев  Дворянское гнездо    350

### Task8

In [225]:
authors_stat = authors_price.groupby('author_name')['price'].agg([('min_price', 'min'), 
                                                                  ('max_price', 'max'), 
                                                                  ('mean_price', 'mean')]).reset_index()
authors_stat


author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000